name: Build and Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "8.0.x"
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish -c Release -p:PublishSingleFile=true --self-contained false
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/ShadowCopyManager*.zip
